version: '3.8'  # Убедитесь, что у вас актуальная версия Compose

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - backend

  backend:
    image: therealyou322/backend:latest
    container_name: backend
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      DATABASE_URL: mongodb://mongo:27017/your-database
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
