version: '3.8'  # Убедитесь, что у вас актуальная версия Compose

services:
  mongo:
    image: mongo:4.4.18
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=mstuca_master'
      - 'MONGO_INITDB_ROOT_PASSWORD=mstuca_master'

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - backend

  backend:
    image: therealyou322/backend:latest
    container_name: backend
    volumes:
      - ./path/to/deploy/files/proxies.txt:/app/files/proxies.txt
    ports:
      - "3004:3004"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      DATABASE_URL: mongodb://mstuca_master:mstuca_master@mongo:27017/
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
      PROXIES_PATH: /app/files/proxies.txt
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
