version: '3.8'

services:
  backend:
    image: therealyou322/backend:latest
    container_name: backend
    ports:
      - "3000:3000"  # Основной порт приложения
      - "3001:3001"  # Дополнительный порт 1
      - "3002:3002"  # Дополнительный порт 2
      - "3003:3003"  # Дополнительный порт 3# Замените на порт вашего приложения
    depends_on:
      - mongo
      - rabbitmq
    environment:
      DATABASE_URL: mongodb://dev:dev@mongo:27017/
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    restart: always

  mongo:
    image: 'mongo:6'
    container_name: 'test_project'
    restart: 'unless-stopped'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=dev'
      - 'MONGO_INITDB_ROOT_PASSWORD=dev'
    ports:
      - '47017:27017'
    networks:
      - 'backend'
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '1m'

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

volumes:
  mongo-data:
