name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t therealyou322/backend:latest .
        docker push therealyou322/backend:latest

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Сохраните приватный ключ в файл
        echo "$SSH_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa

        mkdir -p ~/.ssh

        # Добавьте ключ хоста сервера в known_hosts
        ssh-keyscan -H 185.189.167.8>> ~/.ssh/known_hosts

        # Копируйте файлы на сервер
        scp -i id_rsa docker-compose.yml root@185.189.167.8:/path/to/deploy/
    
        # Подключитесь к серверу и выполните команды
        ssh -i id_rsa root@185.189.167.8<< 'EOF'
          cd /path/to/deploy/
          docker-compose pull
          docker-compose up -d
        EOF

